---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/quickstart-ci
inputs:
- name: tile
- name: quickstart-repo-ci
- name: quickstart-repo
  path: repo
outputs:
- name: repo
run:
  path: quickstart-repo-ci/ci/tasks/update-tile.sh
params:
  PIVNET_TOKEN: replace-me
  TILE_NAME: replace-me
  TILE_BASE_DIR: replace-me
