---
platform: linux
image_resource:
  type: docker-image
  source: quickstart-ci-image
inputs:
- name: tile
- name: aws-quickstart-repo
  path: repo-in
outputs:
- name: repo-out
run:
  path: ci/tasks/update-tile.sh
params:
  PIVNET_TOKEN: replace-me
  TILE_NAME: replace-me
  TILE_BASE_DIR: replace-me
