director:
  manifest: director/config.yml
  ops_files: []
  vars:
    opsman_ssh_key: ((opsman_ssh_key))
# tiles: []
tiles:
- name: cf
  version: 2.5.4
  product:
    product_slug: elastic-runtime
    release_version: 2.5.4
    file_glob: "srt*.pivotal"
  stemcell:
    product_slug: stemcells-ubuntu-xenial
    release_version: "250.56"
    file_glob: "*aws*.tgz"
  manifest: tiles/srt/product.yml
  ops_files:
  - tiles/srt/features/haproxy_forward_tls-disable.yml
  - tiles/srt/features/tcp_routing-enable.yml
  - tiles/srt/features/system_blobstore-external.yml
  - tiles/srt/optional/add-system_blobstore-external-access_key.yml
  - tiles/srt/optional/add-system_blobstore-external-secret_key.yml
  - tiles/srt/optional/add-system_blobstore-external-region.yml
  - tiles/srt/resource/control_elb_names.yml
  - tiles/srt/resource/router_elb_names.yml
  - tiles/srt/resource/tcp_router_elb_names.yml
  vars_files:
  - tiles/srt/product-default-vars.yml
  - tiles/srt/resource-vars.yml
  - tiles/srt/errand-vars.yml
  vars:
    network_name: pcf-ert-network
    singleton_availability_zone: ((PcfAvailabilityZone1))
    cloud_controller/system_domain: sys.((Domain))
    cloud_controller/apps_domain: apps.((Domain))
    networking_poe_ssl_certs_0/name: Certificate
    networking_poe_ssl_certs_0/certificate: ((ssl_cert.certificate))
    networking_poe_ssl_certs_0/privatekey: ((ssl_cert.private_key))
    ha_proxy/skip_cert_verify: true
    haproxy_forward_tls/enable/backend_ca: ((default_ca.ca)))
    credhub_key_encryption_passwords_0/key: ((credhub_encryption_key))
    credhub_key_encryption_passwords_0/name: Default_Key
    credhub_key_encryption_passwords_0/primary: true
    uaa/service_provider_key_credentials/certificate: ((ssl_cert.certificate))
    uaa/service_provider_key_credentials/privatekey: ((ssl_cert.private_key))
    security_acknowledgement: X
    stack_migration_acknowledgement: x
    mysql_monitor/recipient_email: ((AdminEmail))
    control_elb_names: [((PcfElbSshName))]
    router_elb_names: [((PcfElbWebName))]
    tcp_router_elb_names: [((PcfElbTcpName))]
    tcp_routing/enable/reservable_ports: "1024-65535"
    gorouter_ssl_ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    haproxy_ssl_ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    mysql_monitor_instances: 0
    system_blobstore/external/buildpacks_bucket: ((PcfElasticRuntimeS3BuildpacksBucket))
    system_blobstore/external/droplets_bucket: ((PcfElasticRuntimeS3DropletsBucket))
    system_blobstore/external/packages_bucket: ((PcfElasticRuntimeS3PackagesBucket))
    system_blobstore/external/resources_bucket: ((PcfElasticRuntimeS3ResourcesBucket))
    system_blobstore/external/endpoint: https://s3.((Region)).amazonaws.com
    system_blobstore/external/region: ((Region))
    system_blobstore/external/access_key: ((PcfIamUserAccessKey))
    system_blobstore/external/secret_key: ((PcfIamUserSecretAccessKey))
    system_blobstore/external/signature_version: 4
    system_blobstore/external/encryption: false
    system_blobstore/external/iam_instance_profile_authentication: false
    system_blobstore/external/versioning: true

- name: aws-service-broker
  version: 1.0.0-beta.3
  product:
    product_slug: aws-service-broker
    release_version: 1.0.0-beta.3
    file_glob: "aws-service-broker*.pivotal"
    download_url: "https://github.com/awslabs/aws-servicebroker/releases/download/v1.0.0-beta.3/aws-service-broker-1.0.0-beta.3-tile.pivotal"
  stemcell:
    product_slug: stemcells
    release_version: "3586.118"
    file_glob: "*aws*.tgz"
  manifest: tiles/aws-service-broker/product.yml
  ops_files:
  - tiles/aws-service-broker/optional/add-tls_key.yml
  - tiles/aws-service-broker/optional/add-tls_cert.yml
  vars_files:
  - tiles/aws-service-broker/product-default-vars.yml
  - tiles/aws-service-broker/resource-vars.yml
  - tiles/aws-service-broker/errand-vars.yml
  vars:
    network_name: pcf-services-network
    singleton_availability_zone: ((PcfAvailabilityZone1))
    aws_access_key_id: ((BrokerIamUserAccessKey))
    aws_secret_access_key: ((BrokerIamUserSecretAccessKey))
    aws_default_region: ((Region))
    tls_cert: ((ssl_cert.certificate))
    tls_key: ((ssl_cert.private_key))
    insecure: true
    aws_sb_enable_global_access_to_plans: true

variables:
- name: opsman_ssh_key
  type: ssh
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: default
- name: ssl_cert
  type: certificate
  options:
    ca: default_ca
    common_name: ((Domain))
    alternative_names:
      - "*.((Domain))"
      - "*.sys.((Domain))"
      - "*.apps.((Domain))"
      - "*.uaa.sys.((Domain))"
      - "*.login.sys.((Domain))"
- name: credhub_encryption_key
  type: password
  options:
    length: 32
